### ISSUE TITLE
Example implementation?

### ISSUE THREAD

**Issue by riskable** [bjc/bootkbd#1]
I want my Keyberon-based analog keyboard firmware to work in things like the BIOS and Grub's boot menu but I'm not sure how (or if) I could implement this alongside Keyberon's USB HID class stuff.  Even just a basic example showing how this code is used would be helpful.  Thanks!

**Comment by bjc** [comment]
This library is for the host side of the protocol, so it wouldn't be suitable for implementing a keyboard itself (there are crates for that already, I'm sure).

As far as examples, I'm sorry I don't have any that are more clear, but you can see how this is used in another project of mine, which takes input from a boot-protocol USB keyboard and sends it out over I²C:

https://github.com/bjc/bleusb/blob/master/usb/src/main.rs#L138

There's really not a lot going on. First initialize the driver with a callback, which is called as events come in to host from the keyboard's endpoint (which is auto-probed); then attach it to a list of handlers (https://github.com/bjc/bleusb/blob/master/usb/src/main.rs#L144) and finally make sure it gets called regularly:

https://github.com/bjc/bleusb/blob/master/usb/src/main.rs#L162

This all relies on a crate which implements the `usb-host` trait for a given micro controller. As far as I know, the only ones that do right now are for the SAMD series, and that's because I implemented them: https://github.com/bjc/atsamd-usb-host
